### ISSUE TITLE
removeButton is undefined

### ISSUE THREAD

**Issue by Romaixn** [thetechnicalchallenge/collection-type-manager#1]
Hey ! I have a problem with the config..

I followed the documentation but I have this error : 

`Uncaught TypeError: can't access property "addEventListener", removeButton is undefined`

With an empty list (no element)

Thanks !

**Comment by thetechnicalchallenge** [comment]
Hello, 
Sorry, but I probably need more information as I can't reproduce this error.
Can you send me the configuration of `CollectionTypeManager` and the `twig` used for your collections?

Thanks!
